### PR TITLE
Fixed errors running for Landsat 5 and 7 images due to incorrect DOY extraction & B6 filename issues

### PR DESCRIPTION
**Pull request by robintw**
I'm not sure if this code is actively maintained or not, but I found it when I was trying to run the FMask cloud masking
from Python. I found that the code in the repository worked fine for Landsat 8, but not for Landsat 7 or Landsat 5 imagery,
and I've made modifications to fix this.

Specifically, I have:

1) Changed the code which extracts the Day of Year (DOY) from the scene name, as this was incorrectly extracting only part of the DOY.
This had already been fixed for L8, but not for L7 or L5.

2) Rewritten the match_file function to use the Python glob module (included in the standard library), to make it more robust. I'm not quite
sure why, but the previous code was failing to pick up the B6 file for Landsat images (which has B6_VCID_1 and B6_VCID_2) and picking the B1
image instead, which led to very strange results...

### CODE REVIEW

**Comment by ceholden** [comment]
Hi @robintw 

Very happy to merge your PR. As you thought, this project is somewhat abandoned -- I made the GUI as a way of exploring the effect of the parameters on the output and to demonstrate to others that the "defaults" that Fmask's author Zhe Zhu set, which are designed to balance omission and commission of the cloud / shadow mask, are not necessarily what you want depending on your application. For instance, I'm mostly concerned with missing clouds than I am with false positives because I work with timeseries of 300-1200 Landsat images. I got my point across and haven't looked back.

The Python Fmask port is actually from [Geoscience Australia](https://github.com/GeoscienceAustralia) but they haven't hosted it anywhere independently. There are probably some benefits to using this Python version, but I'd be remiss if I didn't point you to the [officially maintained and documented C-code version by the USGS](https://github.com/USGS-EROS/espa-cloud-masking) which they use in their ["ESPA" higher level product ordering system](https://espa.cr.usgs.gov). We get our cloud masks and atmospherically corrected data through ESPA nowadays and use either the MATLAB compiled runtime or the C-code version for making masks with non-default parameters.

That DOY mixup is especially embarassing -- I shouldn't have trusted the comment about the indexing!

Cheers
Chris

**Comment by robintw** [comment]
Thanks Chris.

Yes, I'm also interested in the effect of different parameters, as I'm using Landsat images for air quality monitoring and so want to make extra sure that I don't include any clouds by accident, and thus inflate the air quality estimates.

I am aware of the USGS C version, but found it was a bit of a pain to use in some situations, particularly as it required imagery in an ESPA-specific format. I've got a full Python-based processing chain for my algorithm, and it's quite nice to have a simple Python function I can call to do the cloud masking.

Do you happen to know what license (if any) the original Python port was released under? I see that your QGIS Plugin code is under the GPL, but I'm intrigued as to whether actual Python FMask code has a license. Do you know the people at Geoscience Australia who did the original port?

I don't know what your plans are for this longer-term, but I'm quite keen that a Python version continues to be available, and would be happy to help with maintenance when necessary (eg. next time the USGS change the MTL format, or when Landsat 9 is launched!).

**Comment by ceholden** [comment]
The original MATLAB Fmask code was licensed under GPL v2 and when I received the Python code from GA (through @llymburn and @sixy6e) they indicated that it should be licensed the same as the original Fmask code. 

I'm not sure how they're running Fmask for their [data cubes](https://github.com/GeoscienceAustralia/agdc), but I'll try to reach them via email to see if they have any updates. They were enthusiastic for me to use their code in developing the plugin and I'm sure my PhD advisor and former lab-mate (the Woodcock & Zhu authors, respectively) would be happy to have someone keeping a Python version alive.

Great job wrapping 6S and helping the recipy project, by the way! It's always nice to see other remote sensing scientists using Python.

**Comment by robintw** [comment]
You were supervised by Woodcock, and were lab mates with Zhu? Awesome! I've read a lot of their work.

Yeah, I was very glad to find a Python version of FMask, and it's very nice to see other RS scientists using Python. Thanks for the comments on 6S and recipy - I came up with the idea for recipy at a Hack Day about six months ago, and I'm impressed as to how it has grown now! I've just applied for a bit of funding to develop it further - so fingers crossed!

I'll make sure any version that I do anything with has a GPL v2 license attached, and states where it came from.

**Pull request merged**
